package aplikasigudang;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.connect;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author L E N O V O
 */
public class BarangMasuk extends javax.swing.JFrame {

    private final Connection conn;
    private Statement stat;
    private PreparedStatement pst;
    private ResultSet res;
    private final DefaultTableModel model;

    // kode barang otomatis (property)
    private static String kode;
    private static String kodeTransaksi;

    public BarangMasuk() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        txtkdbarang.setText(kodeTransaksi);
        conn = koneksi.connect.configDB();
        model = new DefaultTableModel();
        // set model table 
        model.addColumn("KODE BARANG");
        model.addColumn("NAMA");
        model.addColumn("QTY");
        model.addColumn("HARGA STOK");
        model.addColumn("HARGA SATUAN");
        model.addColumn("KODE JENIS");
        model.addColumn("TGL KADALUARSA");
        model.addColumn("KODE SUPLIYER");
        tbl_barangMasuk.setModel(model);

        // menambah kode suplier ke combo box
        tambahKodeSuplier();
        tambahjenisbarang();
        // membuat kode barang otomatis
        kodeTransaksiOtomatis();
        // menampilkan data pada tabel
        getData();
    }

    private void kodeTransaksiOtomatis() {
        String sql = "select * from barang_masuk order by kd_barang desc";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                kode = res.getString("kd_barang").substring(1);
                String autoNumber = "" + (Integer.parseInt(kode) + 1);
                String nol = "";

                switch (autoNumber.length()) {
                    case 1:
                        nol = "00";
                        break;
                    case 2:
                        nol = "0";
                        break;
                    case 3:
                        nol = "";
                        break;
                    default:
                        break;
                }

                kodeTransaksi = "B" + nol + autoNumber;
                System.out.println(kodeTransaksi);
            } else {
                kodeTransaksi = "B001";
                System.out.println(kodeTransaksi);
            }
        } catch (NumberFormatException | SQLException e) {
            System.out.println("tidak ada data yang masuk");
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkdbarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txthargastok = new javax.swing.JTextField();
        txthargasatuan = new javax.swing.JTextField();
        btn_baru = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        cb_kode_suplier = new javax.swing.JComboBox<>();
        lbl_nama_supliyer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barangMasuk = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnjb = new javax.swing.JButton();
        cb_jenis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        lbljenis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Kd Barang");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Qty");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Harga Stok");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Harga Satuan");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Tgl Kadaluarsa");

        txtkdbarang.setEditable(false);
        txtkdbarang.setBackground(new java.awt.Color(204, 204, 204));
        txtkdbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdbarangActionPerformed(evt);
            }
        });

        txthargasatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargasatuanActionPerformed(evt);
            }
        });

        btn_baru.setBackground(new java.awt.Color(0, 153, 153));
        btn_baru.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_baru.setText("BARU");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 153, 153));
        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(0, 153, 153));
        btnhapus.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncetak.setBackground(new java.awt.Color(0, 153, 153));
        btncetak.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        btnkeluar.setBackground(new java.awt.Color(0, 153, 153));
        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Kd Supliyer");

        btntambah.setBackground(new java.awt.Color(0, 153, 153));
        btntambah.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        cb_kode_suplier.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_kode_suplierPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbl_nama_supliyer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nama_supliyer.setText("-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nama Supliyer : ");

        tbl_barangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barangMasuk);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang Masuk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );

        btncari.setBackground(new java.awt.Color(0, 153, 153));
        btncari.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Jenis");

        btnjb.setText("Edit Jenis Barang");
        btnjb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjbActionPerformed(evt);
            }
        });

        cb_jenis.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_jenisPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel10.setText("Jenis Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_kode_suplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(587, 587, 587))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txthargasatuan)
                        .addGap(40, 40, 40)
                        .addComponent(btn_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbljenis, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(btnjb))
                            .addComponent(txthargastok, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtqty, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkdbarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_jenis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncari)
                                .addGap(233, 233, 233))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_nama_supliyer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(30, 30, 30))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txthargastok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txthargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_baru)
                            .addComponent(btntambah)
                            .addComponent(btnedit))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnhapus)
                            .addComponent(btncetak)
                            .addComponent(btnkeluar)
                            .addComponent(cb_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncari))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbljenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnjb)
                        .addComponent(jLabel10)))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_kode_suplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_nama_supliyer))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        txtkdbarang.setText("");
        txtkdbarang.setEditable(false);
        txtnamabarang.setText("");
        txtqty.setText("");
        txthargastok.setText("");
        txthargasatuan.setText("");
        cb_jenis.setSelectedIndex(0);
        cb_kode_suplier.setSelectedIndex(0);
        dc_kadaluarsa.setCalendar(null);
        lbl_nama_supliyer.setText("");
        lbljenis.setText("");
    }//GEN-LAST:event_btn_baruActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // mengambil inputan dari setiap field
        String kodeBarang = kodeTransaksi;
        String namaBarang = txtnamabarang.getText();
        int qty = Integer.parseInt(txtqty.getText());
        int hargaStok = Integer.parseInt(txthargastok.getText());
        int hargaSatuan = Integer.parseInt(txthargasatuan.getText());
        String kodejenis = cb_jenis.getSelectedItem().toString();
        String kodeSupliyer = cb_kode_suplier.getSelectedItem().toString();

        // query untuk melakukan tambah data
        try {
            String sql = "insert into barang_masuk(kd_barang, nama_barang, qty, harga_stok, harga_satuan, kode_jenis, tgl_kadaluarsa, kd_supliyer) "
                    + "values (?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kodeBarang);
            pst.setString(2, namaBarang);
            pst.setInt(3, qty);
            pst.setInt(4, hargaStok);
            pst.setInt(5, hargaSatuan);
            pst.setString(6, kodejenis);
            String format = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            String gtl = sdf.format(dc_kadaluarsa.getDate());
            pst.setString(7, gtl);
            pst.setString(8, kodeSupliyer);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah barang masuk berhasil");
            // tampilkan data barang masuk
            getData();
            // kosongkan field
            btn_baruActionPerformed(evt);
            kodeTransaksiOtomatis();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tambah barang masuk gagal");
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btntambahActionPerformed

    private void cb_kode_suplierPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_kode_suplierPopupMenuWillBecomeInvisible
        // untuk menampilkan nama supliyer berdasarkan kodenya
        String kode = cb_kode_suplier.getSelectedItem().toString();
        try {
            String sql = "select nama_supliyer from supliyer where kd_supliyer='" + kode + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                lbl_nama_supliyer.setText(res.getString("nama_supliyer"));
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cb_kode_suplierPopupMenuWillBecomeInvisible

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        // mengambil inputan dari setiap field
        String kodeBarang = kodeTransaksi;
        String namaBarang = txtnamabarang.getText();
        int qty = Integer.parseInt(txtqty.getText());
        int hargaStok = Integer.parseInt(txthargastok.getText());
        int hargaSatuan = Integer.parseInt(txthargasatuan.getText());
        String kodejenis = cb_jenis.getSelectedItem().toString();
        String kodeSupliyer = cb_kode_suplier.getSelectedItem().toString();

        // query untuk melakukan tambah data
        try {
            String sql = "update barang_masuk set nama_barang= ?, qty= ?, harga_stok=?, harga_satuan=?, kode_jenis=?, tgl_kadaluarsa=?, kd_supliyer=? where kd_barang=? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, namaBarang);
            pst.setInt(2, qty);
            pst.setInt(3, hargaStok);
            pst.setInt(4, hargaSatuan);
            pst.setString(5, kodejenis);
            String format = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            String gtl = sdf.format(dc_kadaluarsa.getDate());
            pst.setString(6, gtl);
            pst.setString(7, kodeSupliyer);
            pst.setString(8, txtkdbarang.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Update barang masuk berhasil");
            // tampilkan data barang masuk
            getData();
            // kosongkan field
            btn_baruActionPerformed(evt);
            kodeTransaksiOtomatis();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Update barang masuk gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tbl_barangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMasukMouseClicked
        // TODO add your handling code here:
        kodeTransaksi = txtkdbarang.getText();
        int i = tbl_barangMasuk.getSelectedRow();
        String kd_barang = model.getValueAt(i, 0).toString();
        String sql = "select * from barang_masuk where kd_barang='" + kd_barang + "'";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txtkdbarang.setText(kd_barang);
                txtnamabarang.setText(res.getString("nama_barang"));
                txtqty.setText(res.getString("qty"));
                txthargastok.setText(res.getString("harga_stok"));
                txthargasatuan.setText(res.getString("harga_satuan"));
                cb_jenis.setSelectedItem(res.getString("kode_jenis"));
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 6));
                dc_kadaluarsa.setDate(date);
                cb_kode_suplier.setSelectedItem(res.getString("kd_supliyer"));
                kodeTransaksi = "";
            }
        } catch (SQLException | ParseException e) {
        }
    }//GEN-LAST:event_tbl_barangMasukMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtkdbarang.getText();
        
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) connect.configDB().createStatement();
            statement.executeUpdate("DELETE from barang_masuk where kd_barang=('" + kd_barang +"');");
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                txtkdbarang.setText("");
                txtnamabarang.setText("");
                txtqty.setText("");
                txthargastok.setText("");
                txthargasatuan.setText("");
                cb_jenis.setSelectedItem(res.getString(""));
            Date date = null;
                dc_kadaluarsa.setDate(date);
                cb_kode_suplier.setSelectedItem(res.getString(""));
        }catch (HeadlessException | SQLException t) {
            JOptionPane.showMessageDialog(null, "data dihapus");
        }

        getData();
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        Connection connect = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Supliyer.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            connect = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gudang", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Supliyer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String file = "D:\\NetBeansProjects\\aplikasigudang\\src\\report\\laporanBarangMasuk.jrxml";
        JasperReport jr;
        try {
            jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, connect);
            JasperViewer.viewReport(jp);
        } catch (JRException ex){
            Logger.getLogger(Supliyer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void txthargasatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargasatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargasatuanActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtkdbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdbarangActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) connect.configDB().createStatement();
            ResultSet res = statement.executeQuery("select * from barang_masuk where " 
                + "kd_barang='" +txtcari.getText() + "'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("kd_barang");
            tbl.addColumn("nama_barang");
            tbl.addColumn("qty");
            tbl.addColumn("harga_stok");
            tbl.addColumn("harga_satuan");
            tbl.addColumn("kode_jenis");
            tbl.addColumn("tgl_kadaluarta");
            tbl.addColumn("kd_supliyer");
            
            tbl_barangMasuk.setModel(tbl);
            while (res.next()){
                tbl.addRow(new Object[]{
                    res.getString("kd_barang"),
                    res.getString("nama_barang"),
                    res.getString("qty"),
                    res.getString("harga_stok"),
                    res.getString("harga_satuan"),
                    res.getString("kode_jenis"),
                    res.getString("tgl_kadaluarsa"),
                    res.getString("kd_supliyer")
                });
            tbl_barangMasuk.setModel(tbl);
                }
            }catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "salah");       
            }
    }//GEN-LAST:event_btncariActionPerformed

    private void btnjbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjbActionPerformed
        // TODO add your handling code here:
        jenisbarang jenisbarang= new jenisbarang();
        jenisbarang.setVisible(true);
    }//GEN-LAST:event_btnjbActionPerformed

    private void cb_jenisPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_jenisPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String kode = cb_jenis.getSelectedItem().toString();
        try {
            String sql = "select jenis_barang from jenis_barang where kode_jenis='" + kode + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                lbljenis.setText(res.getString("jenis_barang"));
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_cb_jenisPopupMenuWillBecomeInvisible
    public static String tanggal_kadaluarsa;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BarangMasuk().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnjb;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JComboBox<String> cb_kode_suplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nama_supliyer;
    private javax.swing.JLabel lbljenis;
    private javax.swing.JTable tbl_barangMasuk;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthargasatuan;
    private javax.swing.JTextField txthargastok;
    private javax.swing.JTextField txtkdbarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

    private void tambahKodeSuplier() {
        try {
            String sql = "select * from supliyer";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                cb_kode_suplier.addItem(res.getString("kd_supliyer"));
            }
        } catch (SQLException e) {
        }
    }
    
     private void tambahjenisbarang() {
        try {
            String sql = "select * from jenis_barang";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                cb_jenis.addItem(res.getString("kode_jenis"));
            }
        } catch (SQLException e) {
        }
    }

    private void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = "select * from barang_masuk";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[8];
                o[0] = res.getString("kd_barang");
                o[1] = res.getString("nama_barang");
                o[2] = res.getString("qty");
                o[3] = res.getString("harga_stok");
                o[4] = res.getString("harga_satuan");
                o[5] = res.getString("kode_jenis");
                o[6] = res.getString("tgl_kadaluarsa");
                o[7] = res.getString("kd_supliyer");
                model.addRow(o);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }
}
