package aplikasigudang;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.connect;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author L E N O V O
 */
public class BarangKeluar extends javax.swing.JFrame {
    private final Connection conn;
    private Statement stat;
    private PreparedStatement pst;
    private ResultSet res;
    private final DefaultTableModel model;

    // kode barang otomatis (property)
    private static String kode;
    private static String kodeTransaksi;

    /**
     * Creates new form BarangKeluar
     */
    public BarangKeluar() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        txtkdbarangkeluar.setText(kodeTransaksi);
        conn = koneksi.connect.configDB();
        model = new DefaultTableModel();
        // set model table 
        model.addColumn("KODE BARANG KELUAR");
        model.addColumn("KODE BARANG");
        model.addColumn("NAMA BARANG");
        model.addColumn("QTY");
        model.addColumn("TGL KADALUARSA");
        model.addColumn("HARGA STOK");
        model.addColumn("KODE SUPLIYER");
        tbl_barangkeluar.setModel(model);

        tambahkodebarang();
        // menambah kode suplier ke combo box
        tambahKodeSupliyer();
        // membuat kode barang otomatis
        kodeTransaksiOtomatis();
        // menampilkan data pada tabel
        getData();
    }
    
    private void kodeTransaksiOtomatis() {
        String sql = "select * from barang_keluar order by kd_barang_keluar desc";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                kode = res.getString("kd_barang_keluar").substring(1);
                String autoNumber = "" + (Integer.parseInt(kode) + 1);
                String nol = "";

                switch (autoNumber.length()) {
                    case 1:
                        nol = "00";
                        break;
                    case 2:
                        nol = "0";
                        break;
                    case 3:
                        nol = "";
                        break;
                    default:
                        break;
                }

                kodeTransaksi = "K" + nol + autoNumber;
                System.out.println(kodeTransaksi);
            } else {
                kodeTransaksi = "K001";
                System.out.println(kodeTransaksi);
            }
        } catch (NumberFormatException | SQLException e) {
            System.out.println("tidak ada data yang masuk");
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtkdbarangkeluar = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txthargastok = new javax.swing.JTextField();
        btnbaru = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barangkeluar = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cb_kode_supliyer = new javax.swing.JComboBox<>();
        lbl_nama_supliyer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_kode_barang = new javax.swing.JComboBox<>();
        dc_kadaluarsa = new com.toedter.calendar.JDateChooser();
        txtnama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Kd Barang Keluar");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Kd Barang");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("Qty");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Tgl Kadaluarsa");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Harga Stok");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("ID Supliyer");

        txtkdbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkdbarangkeluarActionPerformed(evt);
            }
        });

        txthargastok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargastokActionPerformed(evt);
            }
        });

        btnbaru.setBackground(new java.awt.Color(0, 153, 153));
        btnbaru.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnbaru.setText("BARU");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });

        btntambah.setBackground(new java.awt.Color(0, 153, 153));
        btntambah.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(0, 153, 153));
        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(0, 153, 153));
        btnhapus.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncetak.setBackground(new java.awt.Color(0, 153, 153));
        btncetak.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btncetak.setText("CETAK");

        btnkeluar.setBackground(new java.awt.Color(0, 153, 153));
        btnkeluar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barang Keluar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tbl_barangkeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barangkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangkeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barangkeluar);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("CARI");

        cb_kode_supliyer.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_kode_supliyerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbl_nama_supliyer.setText("-");

        jLabel9.setText("Nama Supliyer :");

        cb_kode_barang.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_kode_barangPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnbaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthargastok)
                            .addComponent(txtkdbarangkeluar)
                            .addComponent(cb_kode_supliyer, 0, 379, Short.MAX_VALUE)
                            .addComponent(cb_kode_barang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtqty, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dc_kadaluarsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnama))))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nama_supliyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(btncetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(btnkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(163, 163, 163))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkdbarangkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txthargastok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_kode_supliyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nama_supliyer)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cb_kode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dc_kadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbaru)
                    .addComponent(btntambah)
                    .addComponent(btnedit)
                    .addComponent(btnhapus)
                    .addComponent(btncetak)
                    .addComponent(btnkeluar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txthargastokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargastokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargastokActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
        // TODO add your handling code here:
        txtkdbarangkeluar.setText("");
        cb_kode_barang.setSelectedIndex(0);
        txtnama.setText("");
        txtqty.setText("");
        dc_kadaluarsa.setCalendar(null);
        txthargastok.setText("");
        cb_kode_supliyer.setSelectedIndex(0);
        lbl_nama_supliyer.setText("");
    }//GEN-LAST:event_btnbaruActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String kodebarangkeluar = kodeTransaksi;
        String kodebarang = cb_kode_barang.getSelectedItem().toString();
        String namabarang = txtnama.getText().toString();
        String qty = txtqty.getText().toString();
        String hargaStok = txthargastok.getText().toString();
        String kodeSupliyer = cb_kode_supliyer.getSelectedItem().toString();

        // query untuk melakukan tambah data
        try {
            String sql = "insert into barang_keluar(kd_barang_keluar, kd_barang, nama_barang, qty_keluar, tgl_kadaluarsa, harga_stok, kd_supliyer) "
                    + "values (?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kodebarangkeluar);
            pst.setString(2, kodebarang);
            pst.setString(3, namabarang);
            pst.setString(4, qty);
            String format = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            String gtl = sdf.format(dc_kadaluarsa.getDate());
            pst.setString(5, gtl);
            pst.setString(6, hargaStok);
            pst.setString(7, kodeSupliyer);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Tambah barang keluar berhasil");
            // tampilkan data barang masuk
            getData();
            // kosongkan field
            btn_baruActionPerformed(evt);
            kodeTransaksiOtomatis();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
            System.out.println(e.getMessage());
        }

    }                                         

    private void cb_kode_suplierPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                             
        // untuk menampilkan nama supliyer berdasarkan kodenya
        String kode = cb_kode_supliyer.getSelectedItem().toString();
        try {
            String sql = "select nama_supliyer from supliyer where kd_supliyer='" + kode + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                lbl_nama_supliyer.setText(res.getString("nama_supliyer"));
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        String kodebarangkeluar = kodeTransaksi;
        String kd_barang = cb_kode_barang.getSelectedItem().toString(); 
        String namaBarang = txtnama.getText();
        String qty = txtqty.getText();
        String hargaStok = txthargastok.getText();
        String kodeSupliyer = cb_kode_supliyer.getSelectedItem().toString();

        // query untuk melakukan tambah data
        try {
            String sql = "update barang_keluar set kd_barang=?, nama_barang= ?, qty_keluar= ?, harga_stok=?, tgl_kadaluarsa=?, kd_supliyer=? where kd_barang_keluar=? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, kd_barang);
            pst.setString(2, namaBarang);
            pst.setString(3, qty);
            String format = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            String gtl = sdf.format(dc_kadaluarsa.getDate());
            pst.setString(4, gtl);
            pst.setString(5, hargaStok);
            pst.setString(6, kodeSupliyer);
            pst.setString(7, txtkdbarangkeluar.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Update barang masuk berhasil");
            // tampilkan data barang masuk
            getData();
            // kosongkan field
            btn_baruActionPerformed(evt);
            kodeTransaksiOtomatis();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Update barang masuk gagal");
            System.out.println(e.getMessage());
        }
    }                                       

    private void tbl_barangMasukMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        kodeTransaksi = txtkdbarangkeluar.getText();
        int i = tbl_barangkeluar.getSelectedRow();
        String kd_barang_keluar = model.getValueAt(i, 0).toString();
        String sql = "select * from barang_keluar where kd_barang_keluar='" + kd_barang_keluar + "'";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txtkdbarangkeluar.setText(kd_barang_keluar);
                txtkdbarangkeluar.setText("kd_barang_keluar");
                cb_kode_barang.setSelectedItem(res.getString("kd_barang"));
                txtqty.setText(res.getString("qty_kaluar"));
                txthargastok.setText(res.getString("harga_stok"));
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 5));
                dc_kadaluarsa.setDate(date);
                cb_kode_supliyer.setSelectedItem(res.getString("kd_supliyer"));
                kodeTransaksi = "";
            }
        } catch (SQLException | ParseException e) {
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String kd_barang_keluar = txtkdbarangkeluar.getText();
        
        try {
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) connect.configDB().createStatement();
            statement.executeUpdate("DELETE from barang_keluar where kd_barang_keluar=('" + kd_barang_keluar +"');");
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                txtkdbarangkeluar.setText("");
                cb_kode_barang.setSelectedItem(res.getString(""));
                txtnama.setText("");
                txtqty.setText("");
                txthargastok.setText("");
            Date date = null;
                dc_kadaluarsa.setDate(date);
                cb_kode_supliyer.setSelectedItem(res.getString(""));
        }catch (HeadlessException | SQLException t) {
            JOptionPane.showMessageDialog(null, "data dihapus");
        }

        getData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void cb_kode_barangPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_kode_barangPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String kode = cb_kode_barang.getSelectedItem().toString();
        try {
            String sql = "select * from barang_masuk where kd_barang='" + kode + "'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txtnama.setText(res.getString("nama_barang"));
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(res.getString("tgl_kadaluarsa"));
                dc_kadaluarsa.setDate(date);
                
            }
        } catch (SQLException e) {
        } catch (ParseException ex) {
            Logger.getLogger(BarangKeluar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_kode_barangPopupMenuWillBecomeInvisible

    private void cb_kode_supliyerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_kode_supliyerPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String kode = cb_kode_supliyer.getSelectedItem().toString();
        try {
            int i = 0;
            String sql1 = "SELECT supliyer.nama_supliyer FROM barang_masuk, supliyer WHERE "
                    + "barang_masuk.kd_barang ='"+model.getValueAt(i, 0).toString()+"' "
                    + "AND barang_masuk.kd_supliyer = '"+cb_kode_supliyer.getSelectedItem().toString()+"'";
            stat = conn.createStatement();
            res = stat.executeQuery(sql1);
            if (res.next()) {
                lbl_nama_supliyer.setText("nama_supliyer");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cb_kode_supliyerPopupMenuWillBecomeInvisible

    private void txtkdbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkdbarangkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkdbarangkeluarActionPerformed

    private void tbl_barangkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangkeluarMouseClicked
        // TODO add your handling code here:
        kodeTransaksi = txtkdbarangkeluar.getText();
        int i = tbl_barangkeluar.getSelectedRow();
        String kd_barangkeluar = model.getValueAt(i, 0).toString();
        String sql = "select * from barang_keluar ";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            if (res.next()) {
                txtkdbarangkeluar.setText(kd_barangkeluar);
                cb_kode_barang.setSelectedItem(res.getString("kd_barang"));
                txtnama.setText(res.getString("nama_barang"));
                txtqty.setText(res.getString("qty_keluar"));
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 4));
                dc_kadaluarsa.setDate(date);
                txthargastok.setText(res.getString("harga_stok"));
                cb_kode_supliyer.setSelectedItem(res.getString("kd_supliyer"));
                kodeTransaksi = "";
            }
        } catch (SQLException | ParseException e) {
        }
    }//GEN-LAST:event_tbl_barangkeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BarangKeluar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cb_kode_barang;
    private javax.swing.JComboBox<String> cb_kode_supliyer;
    private com.toedter.calendar.JDateChooser dc_kadaluarsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_nama_supliyer;
    private javax.swing.JTable tbl_barangkeluar;
    private javax.swing.JTextField txthargastok;
    private javax.swing.JTextField txtkdbarangkeluar;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

    private void tambahkodebarang() {
        try {
            String sql = "select * from barang_masuk";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                cb_kode_barang.addItem(res.getString("kd_barang"));
            }
        } catch (SQLException e) {
        }
    }
    private void tambahKodeSupliyer() {
        try {
            String sql = "select * from supliyer";
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                cb_kode_supliyer.addItem(res.getString("kd_supliyer"));
            }
        } catch (SQLException e) {
        }
    }

    private void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String sql = "select * from barang_keluar";
        try {
            stat = conn.createStatement();
            res = stat.executeQuery(sql);
            while (res.next()) {
                Object[] o = new Object[7];
                o[0] = res.getString("kd_barang_keluar");
                o[1] = res.getString("kd_barang");
                o[2] = res.getString("nama_barang");
                o[3] = res.getString("qty_keluar");
                o[4] = res.getString("tgl_kadaluarsa");
                o[5] = res.getString("harga_stok");
                o[6] = res.getString("kd_supliyer");
                model.addRow(o);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }

    private void btn_baruActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
